config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'articles#home'
  get '/about', to: 'articles#about'

  #get '/articles/new', :to => 'articles#new', as: 'new_article'
  #get '/articles/:id/edit', :to => 'articles#edit', as: 'edit_article'
  #get '/articles/:id', :to => 'articles#show', as: 'articles'
  #patch '/articles/:id', :to => 'articles#update'
  #put '/articles/:id', :to => 'articles#update'
  #delete '/articles/:id', :to => 'articles#destroy'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @article = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article was successfully created"
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = "Article succesfully destroyed"
    redirect_to articles_path
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was succesfully updated "
      redirect_to article_path(@article)
    else
      render 'edit'
    end
    flash[:notice] = "Article succesfully updated"
  end

  private
  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
  protect_from_forgery with: :exception

  def home

  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/about.html.erb
<h1>
  Hi! My name is Omair and now im learning RoR.
</h1>

app/views/articles/edit.html.erb
<h1 align="center"> Edit article</h1>

<%= render 'shared/errors', obj: @article %>


<div class="row">
  <div class="col-xs-12">

    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label  col-sm-2">
            <%= f.label :title %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label  col-sm-2">
            <%= f.label :description %>
          </div>
          <div class="col-sm-8">
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: "btn btn-primary btn-lg" %>
          </div>
        </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to 'Cancel request and return to all articles', articles_path %> ]
    </div>

  </div>
</div>

app/views/articles/home.html.erb
<div class="center jumbotron">
  <h1>
    ALPHA BLOG
  </h1>
  <%= link_to 'Sign up now', "#", class: "btn btn-dangerbtn-lg btn-xlarge" %>
</div>

app/views/articles/index.html.erb
<h1> Showing all articles </h1>
<p>
  <%= link_to "Create new article", new_article_path %>
</p>

<table>
  <tr>
    <th> Title </th>
    <th> Description </th>
  </tr>

  <% @article.each do |article| %>
      <tr>
        <td> <%= article.title %> </td>
        <td> <%= article.description %></td>
        <td> <%= link_to 'Edit', edit_article_path(article) %></td>
        <td> <%= link_to 'Show', article_path(article) %></td>
        <td> <%= link_to 'Delete', articles_path(article), method: :delete, data: { confirm: "Are you sure" } %></td>
      </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1 align="center"> Create a new Article </h1>

<%= render 'shared/errors', obj: @article %>


<div class="row">
  <div class="col-xs-12">

    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label  col-sm-2">
              <%= f.label :title %>
          </div>
          <div class="col-sm-8">
           <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
          </div>
         </div>
        <div class="form-group">
          <div class="control-label  col-sm-2">
            <%= f.label :description %>
          </div>
          <div class="col-sm-8">
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
          </div>
        </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to 'Cancel request and return to all articles', articles_path %> ]
    </div>

  </div>
</div>

app/views/articles/show.html.erb
<h2 align="center"> Title: <%= @article.title %> </h2>

<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center description">
    <strong>
      Description:
    </strong>
  </h4>
  <hr> <%= simple_format(@article.description) %> </hr>
  <div class="article-actions">
    <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete this article", articles_path(@article),
                method: :delete, data: { confirm: "Are you sure want  to delete this article"},
                class: "btn btn-xs btn-danger" %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="https://www.udemy.com"> The complete ruby on rails developer</a>
    </small>
    <nav>
      <ul>
        <li>
          <%= link_to "About", about_path %>
        </li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to "Articles", articles_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li> <%= link_to "New Article", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
              prohibited this article from begin saved:
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li> <%= msg %> </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
    <div class='alert alert-<%= "#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
        <% end %>
  </div>
</div>